name: Integration

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

job:
  build:
    
    runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      - uses: action/setup-java@v1
        with:
          java-version: "20.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test